const players = [
    { id: 1, name: "Virat Kohli", nation: "India", trophies: ["ICC World Cup", "Asia Cup"], iplTeams: ["Royal Challengers Bangalore"] },
    { id: 2, name: "AB de Villiers", nation: "South Africa", trophies: ["Champions Trophy"], iplTeams: ["Royal Challengers Bangalore", "Delhi Daredevils"] },
    { id: 3, name: "MS Dhoni", nation: "India", trophies: ["ICC World Cup", "T20 World Cup", "IPL"], iplTeams: ["Chennai Super Kings", "Rising Pune Supergiant"] },
    { id: 4, name: "Chris Gayle", nation: "West Indies", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Punjab Kings", "Royal Challengers Bangalore", "Kolkata Knight Riders"] },
    { id: 5, name: "Sachin Tendulkar", nation: "India", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Mumbai Indians"] },
    { id: 6, name: "Rohit Sharma", nation: "India", trophies: ["ICC World Cup", "IPL", "Asia Cup"], iplTeams: ["Mumbai Indians", "Deccan Chargers"] },
    { id: 7, name: "David Warner", nation: "Australia", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Delhi Capitals", "Sunrisers Hyderabad"] },
    { id: 8, name: "Kane Williamson", nation: "New Zealand", trophies: ["ICC World Test Championship"], iplTeams: ["Sunrisers Hyderabad", "Gujarat Titans"] },
    { id: 9, name: "Ben Stokes", nation: "England", trophies: ["ICC World Cup", "T20 World Cup"], iplTeams: ["Chennai Super Kings", "Rajasthan Royals"] },
    { id: 10, name: "Rashid Khan", nation: "Afghanistan", trophies: ["Asia Cup"], iplTeams: ["Gujarat Titans", "Sunrisers Hyderabad"] },
    { id: 11, name: "Hardik Pandya", nation: "India", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Mumbai Indians", "Gujarat Titans"] },
    { id: 12, name: "Andre Russell", nation: "West Indies", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Kolkata Knight Riders", "Delhi Daredevils"] },
    { id: 13, name: "Jasprit Bumrah", nation: "India", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Mumbai Indians"] },
    { id: 14, name: "Babar Azam", nation: "Pakistan", trophies: ["Asia Cup"], iplTeams: ["No IPL Team"] },
    { id: 15, name: "Steve Smith", nation: "Australia", trophies: ["ICC World Cup", "Ashes"], iplTeams: ["Rajasthan Royals", "Pune Warriors India", "Rising Pune Supergiant", "Delhi Daredevils"] },
    { id: 16, name: "Faf du Plessis", nation: "South Africa", trophies: ["Champions Trophy"], iplTeams: ["Royal Challengers Bangalore", "Chennai Super Kings", "Rising Pune Supergiant"] },
    { id: 17, name: "Shubman Gill", nation: "India", trophies: ["IPL"], iplTeams: ["Gujarat Titans", "Kolkata Knight Riders"] },
    { id: 18, name: "Yuvraj Singh", nation: "India", trophies: ["ICC World Cup", "T20 World Cup", "IPL"], iplTeams: ["Punjab Kings", "Mumbai Indians", "Delhi Daredevils", "Sunrisers Hyderabad", "Royal Challengers Bangalore", "Pune Warriors India"] },
    { id: 19, name: "Sunil Narine", nation: "West Indies", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Kolkata Knight Riders"] },
    { id: 20, name: "Dwayne Bravo", nation: "West Indies", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Chennai Super Kings", "Gujarat Lions", "Mumbai Indians"] },
    { id: 21, name: "Mohammed Shami", nation: "India", trophies: ["IPL"], iplTeams: ["Gujarat Titans", "Punjab Kings", "Delhi Daredevils"] },
    { id: 22, name: "Trent Boult", nation: "New Zealand", trophies: ["ICC World Test Championship"], iplTeams: ["Rajasthan Royals", "Mumbai Indians", "Delhi Daredevils"] },
    { id: 23, name: "KL Rahul", nation: "India", trophies: ["Asia Cup"], iplTeams: ["Lucknow Super Giants", "Punjab Kings", "Royal Challengers Bangalore"] },
    { id: 24, name: "Ravi Ashwin", nation: "India", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Rajasthan Royals", "Chennai Super Kings", "Punjab Kings", "Delhi Capitals"] },
    { id: 25, name: "Shane Watson", nation: "Australia", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Chennai Super Kings", "Rajasthan Royals", "Royal Challengers Bangalore"] },
    { id: 26, name: "Glenn Maxwell", nation: "Australia", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Royal Challengers Bangalore", "Punjab Kings", "Delhi Daredevils"] },
    { id: 27, name: "Pat Cummins", nation: "Australia", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Kolkata Knight Riders", "Delhi Daredevils", "Mumbai Indians"] },
    { id: 28, name: "Ishan Kishan", nation: "India", trophies: ["IPL"], iplTeams: ["Mumbai Indians", "Gujarat Lions"] },
    { id: 29, name: "Suryakumar Yadav", nation: "India", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Mumbai Indians", "Kolkata Knight Riders"] },
    { id: 30, name: "Ruturaj Gaikwad", nation: "India", trophies: ["IPL"], iplTeams: ["Chennai Super Kings"] },
    { id: 31, name: "Mitchell Starc", nation: "Australia", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Kolkata Knight Riders", "Royal Challengers Bangalore"] },
    { id: 32, name: "Sam Curran", nation: "England", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Punjab Kings", "Chennai Super Kings"] },
    { id: 33, name: "Josh Hazlewood", nation: "Australia", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Royal Challengers Bangalore", "Chennai Super Kings"] },
    { id: 34, name: "Deepak Chahar", nation: "India", trophies: ["IPL"], iplTeams: ["Chennai Super Kings", "Rising Pune Supergiant"] },
    { id: 35, name: "Marcus Stoinis", nation: "Australia", trophies: ["T20 World Cup"], iplTeams: ["Lucknow Super Giants", "Delhi Capitals", "Punjab Kings"] },
  { id: 36, name: "Adam Zampa", nation: "Australia", trophies: ["T20 World Cup"], iplTeams: ["Rajasthan Royals", "Royal Challengers Bangalore"] },
  { id: 37, name: "Eoin Morgan", nation: "England", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Kolkata Knight Riders", "Sunrisers Hyderabad"] },
  { id: 38, name: "Jason Roy", nation: "England", trophies: ["ICC World Cup"], iplTeams: ["Kolkata Knight Riders", "Delhi Capitals"] },
  { id: 39, name: "Shreyas Iyer", nation: "India", trophies: ["IPL"], iplTeams: ["Kolkata Knight Riders", "Delhi Capitals"] },
  { id: 40, name: "Rishabh Pant", nation: "India", trophies: ["IPL"], iplTeams: ["Delhi Capitals"] },
  { id: 41, name: "Navdeep Saini", nation: "India", trophies: ["IPL"], iplTeams: ["Rajasthan Royals", "Royal Challengers Bangalore"] },
  { id: 42, name: "Mohammad Nabi", nation: "Afghanistan", trophies: ["T20 World Cup"], iplTeams: ["Sunrisers Hyderabad", "Kolkata Knight Riders"] },
  { id: 43, name: "Liam Livingstone", nation: "England", trophies: ["T20 World Cup"], iplTeams: ["Punjab Kings", "Rajasthan Royals"] },
  { id: 44, name: "Devdutt Padikkal", nation: "India", trophies: ["IPL"], iplTeams: ["Rajasthan Royals", "Royal Challengers Bangalore"] },
  { id: 45, name: "Rahul Tripathi", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad", "Kolkata Knight Riders", "Rising Pune Supergiant"] },
  { id: 46, name: "Prithvi Shaw", nation: "India", trophies: ["ICC U19 World Cup", "IPL"], iplTeams: ["Delhi Capitals"] },
  { id: 47, name: "Varun Chakravarthy", nation: "India", trophies: ["IPL"], iplTeams: ["Kolkata Knight Riders", "Punjab Kings"] },
  { id: 48, name: "Chris Woakes", nation: "England", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Delhi Capitals", "Kolkata Knight Riders", "Royal Challengers Bangalore"] },
  { id: 49, name: "Jofra Archer", nation: "England", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Mumbai Indians", "Rajasthan Royals"] },
  { id: 50, name: "David Miller", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Punjab Kings", "Rajasthan Royals"] },
  { id: 51, name: "Bhuvneshwar Kumar", nation: "India", trophies: ["Champions Trophy", "IPL"], iplTeams: ["Sunrisers Hyderabad", "Pune Warriors India"] },
  { id: 52, name: "Axar Patel", nation: "India", trophies: ["Asia Cup", "IPL"], iplTeams: ["Delhi Capitals", "Punjab Kings"] },
  { id: 53, name: "Kieron Pollard", nation: "West Indies", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Mumbai Indians"] },
  { id: 54, name: "Moeen Ali", nation: "England", trophies: ["ICC World Cup", "T20 World Cup"], iplTeams: ["Chennai Super Kings", "Royal Challengers Bangalore"] }
 , { id: 55, name: "Ravindra Jadeja", nation: "India", trophies: ["ICC World Cup", "Champions Trophy", "IPL"], iplTeams: ["Chennai Super Kings", "Gujarat Lions", "Rajasthan Royals"] },
  { id: 56, name: "Shikhar Dhawan", nation: "India", trophies: ["Champions Trophy", "Asia Cup", "IPL"], iplTeams: ["Punjab Kings", "Delhi Capitals", "Mumbai Indians", "Sunrisers Hyderabad"] },
  { id: 57, name: "Kuldeep Yadav", nation: "India", trophies: ["Asia Cup", "IPL"], iplTeams: ["Delhi Capitals", "Kolkata Knight Riders"] },
  { id: 58, name: "Washington Sundar", nation: "India", trophies: ["Asia Cup", "IPL"], iplTeams: ["Sunrisers Hyderabad", "Royal Challengers Bangalore", "Rising Pune Supergiant"] },
  { id: 59, name: "T Natarajan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad", "Punjab Kings"] },
  { id: 60, name: "Rahmanullah Gurbaz", nation: "Afghanistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 61, name: "Mark Wood", nation: "England", trophies: ["ICC World Cup"], iplTeams: ["Lucknow Super Giants", "Chennai Super Kings"] },
  { id: 62, name: "Harry Brook", nation: "England", trophies: ["T20 World Cup"], iplTeams: ["Sunrisers Hyderabad"] },
  { id: 63, name: "Nicholas Pooran", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants", "Punjab Kings", "Sunrisers Hyderabad"] },
  { id: 64, name: "Shimron Hetmyer", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Delhi Capitals", "Royal Challengers Bangalore"] },
  { id: 65, name: "Kyle Mayers", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants"] },
  { id: 66, name: "Cameron Green", nation: "Australia", trophies: ["ICC World Cup"], iplTeams: ["Mumbai Indians"] },
  { id: 67, name: "Rilee Rossouw", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals"] },
  { id: 68, name: "Reece Topley", nation: "England", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 69, name: "Phil Salt", nation: "England", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals"] },
  { id: 70, name: "Will Jacks", nation: "England", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 71, name: "Tim David", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 72, name: "Jason Holder", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Sunrisers Hyderabad", "Chennai Super Kings", "Kolkata Knight Riders"] },
  { id: 73, name: "Lungi Ngidi", nation: "South Africa", trophies: ["T20 World Cup"], iplTeams: ["Chennai Super Kings", "Delhi Capitals"] },
  { id: 74, name: "Kagiso Rabada", nation: "South Africa", trophies: ["ICC U19 World Cup"], iplTeams: ["Punjab Kings", "Delhi Capitals"] }
  ,{ id: 75, name: "Jos Buttler", nation: "England", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Rajasthan Royals", "Mumbai Indians"] },
  { id: 76, name: "Quinton de Kock", nation: "South Africa", trophies: ["IPL"], iplTeams: ["Lucknow Super Giants", "Mumbai Indians", "Delhi Daredevils", "Sunrisers Hyderabad"] },
  { id: 77, name: "Anrich Nortje", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals"] },
  { id: 78, name: "Tabraiz Shamsi", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 79, name: "Chris Lynn", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians", "Kolkata Knight Riders"] },
  { id: 80, name: "Aaron Finch", nation: "Australia", trophies: ["T20 World Cup"], iplTeams: ["Kolkata Knight Riders", "Royal Challengers Bangalore", "Sunrisers Hyderabad", "Delhi Daredevils", "Punjab Kings"] },
  { id: 81, name: "David Willey", nation: "England", trophies: ["T20 World Cup"], iplTeams: ["Royal Challengers Bangalore", "Chennai Super Kings"] },
  { id: 82, name: "Ben Cutting", nation: "Australia", trophies: ["IPL"], iplTeams: ["Sunrisers Hyderabad", "Mumbai Indians", "Kolkata Knight Riders"] },
  { id: 83, name: "Dawid Malan", nation: "England", trophies: ["T20 World Cup"], iplTeams: ["Punjab Kings"] },
  { id: 84, name: "Colin Munro", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Daredevils", "Kolkata Knight Riders"] },
  { id: 85, name: "James Neesham", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Punjab Kings", "Delhi Daredevils"] },
  { id: 86, name: "Chris Jordan", nation: "England", trophies: ["T20 World Cup"], iplTeams: ["Chennai Super Kings", "Punjab Kings", "Sunrisers Hyderabad"] },
  { id: 87, name: "Mujeeb Ur Rahman", nation: "Afghanistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Sunrisers Hyderabad"] },
  { id: 88, name: "Umesh Yadav", nation: "India", trophies: ["IPL"], iplTeams: ["Kolkata Knight Riders", "Royal Challengers Bangalore", "Delhi Daredevils"] },
  { id: 89, name: "Mohammad Rizwan", nation: "Pakistan", trophies: ["Asia Cup"], iplTeams: ["No IPL Team"] },
  { id: 90, name: "Shaheen Afridi", nation: "Pakistan", trophies: ["T20 World Cup"], iplTeams: ["No IPL Team"] },
  { id: 91, name: "Fidel Edwards", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers"] },
  { id: 92, name: "Dinesh Karthik", nation: "India", trophies: ["IPL", "Asia Cup"], iplTeams: ["Royal Challengers Bangalore", "Kolkata Knight Riders", "Delhi Daredevils", "Mumbai Indians", "Punjab Kings", "Gujarat Lions"] },
  { id: 93, name: "Ambati Rayudu", nation: "India", trophies: ["IPL"], iplTeams: ["Chennai Super Kings", "Mumbai Indians"] },
  { id: 94, name: "Manish Pandey", nation: "India", trophies: ["IPL"], iplTeams: ["Sunrisers Hyderabad", "Kolkata Knight Riders", "Royal Challengers Bangalore", "Delhi Capitals"] },
  { id: 95, name: "Parthiv Patel", nation: "India", trophies: ["IPL"], iplTeams: ["Royal Challengers Bangalore", "Mumbai Indians", "Chennai Super Kings", "Sunrisers Hyderabad"] },
  { id: 96, name: "Irfan Pathan", nation: "India", trophies: ["T20 World Cup"], iplTeams: ["Delhi Daredevils", "Punjab Kings", "Sunrisers Hyderabad"] },
  { id: 97, name: "Sreesanth", nation: "India", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Rajasthan Royals", "Kings XI Punjab"] },
  { id: 98, name: "Harbhajan Singh", nation: "India", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Mumbai Indians", "Chennai Super Kings", "Kolkata Knight Riders"] },
  { id: 99, name: "Zaheer Khan", nation: "India", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Delhi Daredevils", "Mumbai Indians", "Royal Challengers Bangalore"] },
  { id: 100, name: "Kevin Pietersen", nation: "England", trophies: ["ICC World T20"], iplTeams: ["Delhi Daredevils", "Royal Challengers Bangalore"] }
  ,{ id: 101, name: "Tim Southee", nation: "New Zealand", trophies: ["ICC World Test Championship"], iplTeams: ["Kolkata Knight Riders", "Mumbai Indians", "Royal Challengers Bangalore"] },
  { id: 102, name: "Mitchell Marsh", nation: "Australia", trophies: ["T20 World Cup"], iplTeams: ["Delhi Capitals", "Pune Warriors India", "Sunrisers Hyderabad"] },
  { id: 103, name: "Shane Bond", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 104, name: "Albie Morkel", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Delhi Daredevils"] },
  { id: 105, name: "Michael Hussey", nation: "Australia", trophies: ["ICC World Cup"], iplTeams: ["Chennai Super Kings", "Mumbai Indians"] },
  { id: 106, name: "Brad Hogg", nation: "Australia", trophies: ["ICC World Cup"], iplTeams: ["Kolkata Knight Riders", "Rajasthan Royals"] },
  { id: 107, name: "Jacques Kallis", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 108, name: "Brendon McCullum", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Chennai Super Kings"] },
  { id: 109, name: "Andrew Symonds", nation: "Australia", trophies: ["ICC World Cup"], iplTeams: ["Deccan Chargers", "Mumbai Indians"] },
  { id: 110, name: "Muttiah Muralitharan", nation: "Sri Lanka", trophies: ["ICC World Cup"], iplTeams: ["Royal Challengers Bangalore"] },
  , { id: 111, name: "Nitish Kumar Reddy", nation: "India", trophies: ["Emerging Player of the Season"], iplTeams: ["Sunrisers Hyderabad"] },
  { id: 112, name: "Travis Head", nation: "Australia", trophies: ["Most 4s (2024 IPL)"], iplTeams: ["No IPL Team"] },
  { id: 113, name: "Abhishek Sharma", nation: "India", trophies: ["Most 6s (2024 IPL)"], iplTeams: ["Sunrisers Hyderabad"] },
  { id: 114, name: "Jake Fraser-McGurk", nation: "Australia", trophies: ["Striker of the Season (2024 IPL)"], iplTeams: ["No IPL Team"] },
  { id: 115, name: "Ramandeep Singh", nation: "India", trophies: ["Catch of the Season (2024 IPL)"], iplTeams: ["Mumbai Indians"] },
  { id: 116, name: "Shreyas Iyer", nation: "India", trophies: ["IPL Winner (2024)"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 117, name: "Harshal Patel", nation: "India", trophies: ["Purple Cap (2024 IPL)"], iplTeams: ["Punjab Kings"] },
  { id: 118, name: "Sanju Samson", nation: "India", trophies: ["Third Place (2024 IPL)"], iplTeams: ["Rajasthan Royals"] },
  { id: 119, name: "Faf du Plessis", nation: "South Africa", trophies: ["Fourth Place (2024 IPL)"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 120, name: "Sunil Narine", nation: "West Indies", trophies: ["Most Valuable Player (2024 IPL)"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 121, name: "Tilak Varma", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 122, name: "Rajat Patidar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 123, name: "Sai Sudharsan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans"] },
  { id: 124, name: "Mukesh Kumar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals"] },
  { id: 125, name: "Venkatesh Iyer", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 126, name: "Mayank Agarwal", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad", "Punjab Kings"] },
  { id: 127, name: "Rahul Tewatia", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Rajasthan Royals"] },
  { id: 128, name: "Shivam Dube", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 129, name: "Yashasvi Jaiswal", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 130, name: "Rinku Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 131, name: "Arshdeep Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 132, name: "Ravi Bishnoi", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants"] },
  { id: 133, name: "Shivam Mavi", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Kolkata Knight Riders"] },
  { id: 134, name: "Rahul Chahar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Mumbai Indians"] },
  { id: 135, name: "Krunal Pandya", nation: "India", trophies: ["IPL"], iplTeams: ["Lucknow Super Giants", "Mumbai Indians"] },
  { id: 136, name: "Deepak Hooda", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants", "Punjab Kings"] },
  { id: 137, name: "Avesh Khan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants", "Delhi Capitals"] },
  { id: 138, name: "Riyan Parag", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 139, name: "Umran Malik", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad"] },
  { id: 140, name: "Kartik Tyagi", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad", "Rajasthan Royals"] },
  { id: 141, name: "Mohsin Khan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants"] },
  { id: 142, name: "Yash Dhull", nation: "India", trophies: ["ICC U19 World Cup"], iplTeams: ["Delhi Capitals"] },
  { id: 143, name: "Dewald Brevis", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 144, name: "Rajvardhan Hangargekar", nation: "India", trophies: ["ICC U19 World Cup"], iplTeams: ["Chennai Super Kings"] },
  { id: 145, name: "Tristan Stubbs", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 146, name: "Finn Allen", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 147, name: "Gerald Coetzee", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 148, name: "Noor Ahmad", nation: "Afghanistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans"] },
 { id: 149, name: "Matheesha Pathirana", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 150, name: "Sai Sudharsan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans"] },
  { id: 151, name: "Rilee Rossouw", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals"] },
  { id: 152, name: "Akash Deep", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 153, name: "Mayank Yadav", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants"] },
  { id: 154, name: "Raj Angad Bawa", nation: "India", trophies: ["ICC U19 World Cup"], iplTeams: ["Punjab Kings"] },
  { id: 155, name: "Ramandeep Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 156, name: "Hrithik Shokeen", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 157, name: "Kumar Kartikeya", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 158, name: "Mahipal Lomror", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 159, name: "Anuj Rawat", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 160, name: "Suyash Prabhudessai", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 161, name: "Prashant Solanki", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 162, name: "Mukesh Choudhary", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 163, name: "Simarjeet Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 164, name: "Yash Dayal", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans"] },
  { id: 165, name: "Darshan Nalkande", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans"] },
  { id: 166, name: "Abhinav Manohar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans"] },
  { id: 167, name: "Mohit Sharma", nation: "India", trophies: ["Champions Trophy"], iplTeams: ["Gujarat Titans", "Chennai Super Kings"] },
  { id: 168, name: "Anukul Roy", nation: "India", trophies: ["ICC U19 World Cup"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 169, name: "Harshit Rana", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 170, name: "Suyash Sharma", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] }
  ,{ id: 171, name: "Andrew Tye", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Lions", "Punjab Kings", "Lucknow Super Giants"] },
  { id: 172, name: "Kane Richardson", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Pune Warriors India", "Rajasthan Royals", "Royal Challengers Bangalore", "Mumbai Indians"] },
  { id: 173, name: "Ben Hilfenhaus", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 174, name: "Daniel Christian", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Royal Challengers Bangalore", "Rising Pune Supergiant", "Delhi Daredevils"] },
  { id: 175, name: "Beau Webster", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Pune Warriors India"] },
  { id: 176, name: "Cameron White", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Deccan Chargers", "Sunrisers Hyderabad"] },
  { id: 177, name: "George Bailey", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Chennai Super Kings"] },
  { id: 178, name: "Travis Birt", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Daredevils"] },
  { id: 179, name: "Brad Brach", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
    { id: 180, name: "Mitchell Johnson", nation: "Australia", trophies: ["ICC World Cup"], iplTeams: ["Mumbai Indians", "Punjab Kings", "Kolkata Knight Riders"] },
  { id: 181, name: "Nuwan Zoysa", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers"] },
  { id: 182, name: "Thilan Thushara", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Mumbai Indians"] },
  { id: 183, name: "Akila Dananjaya", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 184, name: "Avantha Fernando", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians", "Delhi Daredevils"] },
  { id: 185, name: "Dilhara Fernando", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians", "Delhi Daredevils", "Chennai Super Kings"] },
  { id: 186, name: "Chamara Kapugedera", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Deccan Chargers", "Kochi Tuskers Kerala", "Pune Warriors India"] },
  { id: 187, name: "Angelo Perera", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Pune Warriors India", "Kochi Tuskers Kerala"] },
  { id: 188, name: "Ajantha Mendis", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Pune Warriors India"] },
  { id: 189, name: "Thilina Kandamby", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 190, name: "Upul Chandana", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 191, name: "Graham Onions", nation: "England", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 192, name: "Ajmal Shahzad", nation: "England", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 193, name: "Riki Wessels", nation: "England", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 194, name: "Yasir Arafat", nation: "Pakistan", trophies: ["T20 World Cup"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 195, name: "Sohail Tanvir", nation: "Pakistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 196, name: "Salman Butt", nation: "Pakistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 197, name: "Mohammad Asif", nation: "Pakistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Daredevils"] },
  { id: 198, name: "Azhar Mahmood", nation: "Pakistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Kolkata Knight Riders"] },
  { id: 199, name: "Abdul Razzaq", nation: "Pakistan", trophies: ["T20 World Cup"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 200, name: "Naved-ul-Hasan", nation: "Pakistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 201, name: "Tamim Iqbal", nation: "Bangladesh", trophies: ["No Major ICC Trophy"], iplTeams: ["Pune Warriors India"] },
  { id: 202, name: "Taskin Ahmed", nation: "Bangladesh", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad"] },
  { id: 203, name: "Elias Sunny", nation: "Bangladesh", trophies: ["No Major ICC Trophy"], iplTeams: ["Pune Warriors India"] },
  { id: 204, name: "Shafiul Islam", nation: "Bangladesh", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 205, name: "Nazimuddin", nation: "Bangladesh", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 206, name: "Sunny Sohal", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Punjab Kings"] },
  { id: 207, name: "Paul Valthaty", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 208, name: "Manvinder Bisla", nation: "India", trophies: ["IPL"], iplTeams: ["Kolkata Knight Riders", "Punjab Kings"] },
  { id: 209, name: "Swapnil Asnodkar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 210, name: "Kamran Khan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals",  "Pune Warriors India"] },
  { id: 211, name: "Pinal Shah", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 212, name: "Taruwar Kohli", nation: "India", trophies: ["ICC U19 World Cup"], iplTeams: ["Rajasthan Royals"] },
  { id: 213, name: "Sam Billings", nation: "England", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Daredevils", "Chennai Super Kings"] },
  { id: 214, name: "Nathan Bracken", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 215, name: "Ryan Harris", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Punjab Kings"] },
  { id: 216, name: "Mitchell McClenaghan", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 217, name: "Rishabh Pant", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals"] },
    { id: 218, name: "Iqbal Abdulla", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Royal Challengers Bangalore"] },
  { id: 219, name: "Pradeep Sangwan", nation: "India", trophies: ["ICC U19 World Cup"], iplTeams: ["Delhi Daredevils", "Gujarat Lions", "Mumbai Indians"] },
  { id: 220, name: "Saurabh Tiwary", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians", "Royal Challengers Bangalore", "Delhi Daredevils"] }
  , { id: 221, name: "Alfonso Thomas", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Pune Warriors India"] },
  { id: 222, name: "Cameron Borgas", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 223, name: "James Hopes", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Daredevils", "Punjab Kings", "Pune Warriors India"] },
  { id: 224, name: "Shaun Tait", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 225, name: "Ashley Noffke", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 226, name: "Callum Ferguson", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Pune Warriors India"] },
  { id: 227, name: "Luke Pomersbach", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Punjab Kings"] },
  { id: 228, name: "Nathan Rimmington", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 229, name: "Daniel Harris", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers"] },
  { id: 230, name: "Tom Moody", nation: "Australia", trophies: ["ICC World Cup"], iplTeams: ["No IPL Team (Coach)"] }, // Tom Moody as coach
  { id: 231, name: "Marlon Samuels", nation: "West Indies", trophies: ["T20 World Cup"], iplTeams: ["Pune Warriors India", "Delhi Daredevils"] },
  { id: 232, name: "Samuel Badree", nation: "West Indies", trophies: ["T20 World Cup"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 233, name: "Krishmar Santokie", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 234, name: "Fidel Edwards", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers"] },
  { id: 235, name: "Darren Bravo", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians", "Kolkata Knight Riders"] },
  { id: 236, name: "Ricardo Powell", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 237, name: "Pedro Collins", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 238, name: "Lendl Simmons", nation: "West Indies", trophies: ["T20 World Cup"], iplTeams: ["Mumbai Indians"] },
  { id: 239, name: "Andre Fletcher", nation: "West Indies", trophies: ["T20 World Cup"], iplTeams: ["Royal Challengers Bangalore", "Sunrisers Hyderabad", "Mumbai Indians"] },
  { id: 240, name: "Carlos Brathwaite", nation: "West Indies", trophies: ["T20 World Cup"], iplTeams: ["Delhi Daredevils", "Sunrisers Hyderabad", "Kolkata Knight Riders"] },
  { id: 241, name: "James Franklin", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 242, name: "Kyle Mills", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 243, name: "Brendon McCullum", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Chennai Super Kings", "Gujarat Lions", "Royal Challengers Bangalore"] },
  { id: 244, name: "Jacob Oram", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Mumbai Indians", "Rajasthan Royals"] },
  { id: 245, name: "Jesse Ryder", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Pune Warriors India"] },
  { id: 246, name: "Ross Taylor", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Delhi Daredevils", "Pune Warriors India", "Rajasthan Royals"] },
  { id: 247, name: "Scott Styris", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Chennai Super Kings"] },
  { id: 248, name: "Grant Elliott", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 249, name: "Ian Butler", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 250, name: "James Neesham", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Daredevils", "Punjab Kings", "Rajasthan Royals"] },
  { id: 251, name: "Dwayne Smith", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Mumbai Indians", "Chennai Super Kings", "Gujarat Lions"] },
  { id: 252, name: "Kemar Roach", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers"] },
  { id: 253, name: "Sunil Narine", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 254, name: "Tino Best", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 255, name: "Shivnarine Chanderpaul", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 256, name: "Corey Anderson", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians", "Delhi Daredevils", "Royal Challengers Bangalore"] },
  { id: 257, name: "Mitchell Santner", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 258, name: "Colin de Grandhomme", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Royal Challengers Bangalore"] },
  { id: 259, name: "Ish Sodhi", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 260, name: "Tim Southee", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Mumbai Indians", "Royal Challengers Bangalore", "Kolkata Knight Riders"] },
  { id: 261, name: "Adam Milne", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Mumbai Indians"] },
  { id: 262, name: "Lockie Ferguson", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Gujarat Titans"] },
  { id: 263, name: "Nathan McCullum", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Pune Warriors India"] },
  { id: 264, name: "Jimmy Maher", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Daredevils"] },
  { id: 265, name: "Michael Klinger", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Kochi Tuskers Kerala"] },
  { id: 266, name: "Nathan Hauritz", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Mumbai Indians", "Royal Challengers Bangalore"] },
  { id: 267, name: "Brad Hogg", nation: "Australia", trophies: ["ICC World Cup"], iplTeams: ["Kolkata Knight Riders", "Rajasthan Royals"] },
  { id: 268, name: "Mark Cosgrove", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 269, name: "Ashley Noffke", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
    { id: 270, name: "Andrew McDonald", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Daredevils", "Royal Challengers Bangalore"] }
    , { id: 271, name: "Thisara Perera", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Kochi Tuskers Kerala", "Mumbai Indians", "Sunrisers Hyderabad"] },
    { id: 272, name: "Johan Botha", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Delhi Daredevils"] },
    { id: 273, name: "Ravi Rampaul", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
    { id: 274, name: "Brad Hodge", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Rajasthan Royals", "Gujarat Lions"] },
    { id: 275, name: "Dimitri Mascarenhas", nation: "England", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Punjab Kings"] },
    { id: 276, name: "Mitchell Johnson", nation: "Australia", trophies: ["ICC World Cup"], iplTeams: ["Mumbai Indians", "Punjab Kings", "Kolkata Knight Riders"] },
    { id: 277, name: "Shane Watson", nation: "Australia", trophies: ["IPL"], iplTeams: ["Rajasthan Royals", "Royal Challengers Bangalore", "Chennai Super Kings"] },
    { id: 278, name: "Irfan Pathan", nation: "India", trophies: ["T20 World Cup"], iplTeams: ["Kings XI Punjab", "Delhi Daredevils", "Sunrisers Hyderabad", "Chennai Super Kings", "Rising Pune Supergiant"] },
    { id: 279, name: "Yusuf Pathan", nation: "India", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Rajasthan Royals", "Kolkata Knight Riders", "Sunrisers Hyderabad"] },
    { id: 280, name: "RP Singh", nation: "India", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Deccan Chargers", "Kochi Tuskers Kerala"] },
    { id: 281, name: "Chaminda Vaas", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers"] },
    { id: 282, name: "Mahela Jayawardene", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Daredevils", "Kochi Tuskers Kerala", "Mumbai Indians"] },
    { id: 283, name: "Kumar Sangakkara", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Sunrisers Hyderabad"] },
    { id: 284, name: "Sanath Jayasuriya", nation: "Sri Lanka", trophies: ["ICC World Cup"], iplTeams: ["Mumbai Indians"] },
    { id: 285, name: "Muttiah Muralitharan", nation: "Sri Lanka", trophies: ["ICC World Cup"], iplTeams: ["Chennai Super Kings", "Royal Challengers Bangalore", "Kochi Tuskers Kerala"] },
    { id: 286, name: "Shoaib Akhtar", nation: "Pakistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
    { id: 287, name: "Shahid Afridi", nation: "Pakistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers"] },
    { id: 288, name: "Abdul Razzaq", nation: "Pakistan", trophies: ["T20 World Cup"], iplTeams: ["Royal Challengers Bangalore"] },
    { id: 289, name: "Umar Gul", nation: "Pakistan", trophies: ["T20 World Cup"], iplTeams: ["Kolkata Knight Riders"] },
    { id: 290, name: "Mohammad Hafeez", nation: "Pakistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
    { id: 291, name: "Brendon McCullum", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Chennai Super Kings", "Gujarat Lions", "Royal Challengers Bangalore"] },
    { id: 292, name: "Ross Taylor", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Delhi Daredevils", "Pune Warriors India", "Rajasthan Royals"] },
    { id: 293, name: "Scott Styris", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Chennai Super Kings"] },
    { id: 294, name: "Kyle Mills", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
    { id: 295, name: "Jacob Oram", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Mumbai Indians", "Rajasthan Royals"] },
    { id: 296, name: "Jesse Ryder", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Pune Warriors India"] },
    { id: 297, name: "James Franklin", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
    { id: 298, name: "Mohammad Ashraful", nation: "Bangladesh", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
    { id: 299, name: "Mashrafe Mortaza", nation: "Bangladesh", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
    { id: 300, name: "Tamim Iqbal", nation: "Bangladesh", trophies: ["No Major ICC Trophy"], iplTeams: ["Pune Warriors India"] },
    { id: 301, name: "Chamara Silva", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers"] },
    { id: 302, name: "Tirumalasetti Suman", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Mumbai Indians", "Pune Warriors India", "Sunrisers Hyderabad"] },
    { id: 303, name: "Pragyan Ojha", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Mumbai Indians"] },
    { id: 304, name: "Andrew Symonds", nation: "Australia", trophies: ["ICC World Cup"], iplTeams: ["Deccan Chargers", "Mumbai Indians"] },
    { id: 305, name: "Adam Gilchrist", nation: "Australia", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Deccan Chargers", "Punjab Kings"] },
    { id: 306, name: "VVS Laxman", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Kochi Tuskers Kerala"] },
    { id: 307, name: "Herschelle Gibbs", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Mumbai Indians"] },
    { id: 308, name: "Rohit Sharma", nation: "India", trophies: ["IPL"], iplTeams: ["Deccan Chargers", "Mumbai Indians"] },
    { id: 309, name: "Mitchell Marsh", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Pune Warriors India", "Sunrisers Hyderabad", "Rising Pune Supergiant"] },
    { id: 310, name: "Albie Morkel", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Royal Challengers Bangalore", "Rising Pune Supergiant", "Delhi Daredevils"] },
    { id: 311, name: "Shaun Marsh", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
    { id: 312, name: "Kumar Sangakkara", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Sunrisers Hyderabad"] },
    { id: 313, name: "Mahela Jayawardene", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Daredevils", "Kochi Tuskers Kerala", "Mumbai Indians"] },
    { id: 314, name: "Lasith Malinga", nation: "Sri Lanka", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Mumbai Indians"] },
    { id: 315, name: "Dilhara Fernando", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians", "Delhi Daredevils", "Chennai Super Kings"] },
    { id: 316, name: "Thisara Perera", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Mumbai Indians",  "Sunrisers Hyderabad"] },
    { id: 317, name: "Yusuf Pathan", nation: "India", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Rajasthan Royals", "Kolkata Knight Riders", "Sunrisers Hyderabad"] },
    { id: 318, name: "Venkat Laxman", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kochi Tuskers Kerala", "Deccan Chargers"] },
    { id: 319, name: "Ajit Agarkar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Daredevils", "Kolkata Knight Riders"] },
    { id: 320, name: "T Natarajan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad", "Punjab Kings"] },
    , { id: 321, name: "Graeme Swann", nation: "England", trophies: ["ICC World Cup", "T20 World Cup"], iplTeams: ["Pune Warriors India"] },
    { id: 322, name: "Michael Clarke", nation: "Australia", trophies: ["ICC World Cup"], iplTeams: ["Pune Warriors India"] },
    { id: 323, name: "Brad Haddin", nation: "Australia", trophies: ["ICC World Cup"], iplTeams: ["Kolkata Knight Riders"] },
    { id: 324, name: "James Faulkner", nation: "Australia", trophies: ["ICC World Cup"], iplTeams: ["Rajasthan Royals", "Gujarat Lions", "Pune Warriors India"] },
    { id: 325, name: "George Bailey", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Chennai Super Kings"] },
    { id: 326, name: "Callum Ferguson", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Pune Warriors India"] },
    { id: 327, name: "Nathan Rimmington", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
    { id: 328, name: "Daniel Harris", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers"] },
    { id: 329, name: "Tom Moody", nation: "Australia", trophies: ["ICC World Cup"], iplTeams: ["No IPL Team (Coach)"] },
    { id: 330, name: "Marlon Samuels", nation: "West Indies", trophies: ["T20 World Cup"], iplTeams: ["Pune Warriors India", "Delhi Daredevils"] },
    { id: 331, name: "Krishmar Santokie", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
    { id: 332, name: "Fidel Edwards", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers"] },
    { id: 333, name: "Darren Bravo", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians", "Kolkata Knight Riders"] },
    { id: 334, name: "Ricardo Powell", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
    { id: 335, name: "Pedro Collins", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
    { id: 336, name: "Lendl Simmons", nation: "West Indies", trophies: ["T20 World Cup"], iplTeams: ["Mumbai Indians"] },
    { id: 337, name: "Andre Fletcher", nation: "West Indies", trophies: ["T20 World Cup"], iplTeams: ["Royal Challengers Bangalore", "Sunrisers Hyderabad", "Mumbai Indians"] },
    { id: 338, name: "Carlos Brathwaite", nation: "West Indies", trophies: ["T20 World Cup"], iplTeams: ["Delhi Daredevils", "Sunrisers Hyderabad", "Kolkata Knight Riders"] },
    { id: 339, name: "James Franklin", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
    { id: 340, name: "Kyle Mills", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
    { id: 341, name: "Brendon McCullum", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Chennai Super Kings", "Gujarat Lions", "Royal Challengers Bangalore"] },
    { id: 342, name: "Jacob Oram", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Mumbai Indians", "Rajasthan Royals"] },
    { id: 343, name: "Jesse Ryder", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Pune Warriors India"] },
    { id: 344, name: "Ross Taylor", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Delhi Daredevils", "Pune Warriors India", "Rajasthan Royals"] },
    { id: 345, name: "Scott Styris", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Chennai Super Kings"] },
    { id: 346, name: "Grant Elliott", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
    { id: 347, name: "Ian Butler", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
    { id: 348, name: "James Neesham", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Daredevils", "Punjab Kings", "Rajasthan Royals"] },
    { id: 349, name: "Dwayne Smith", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers", "Mumbai Indians", "Chennai Super Kings", "Gujarat Lions"] },
    { id: 350, name: "Kemar Roach", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Deccan Chargers"] },
    { id: 351, name: "Sunil Narine", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
    { id: 352, name: "Tino Best", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
    { id: 353, name: "Shivnarine Chanderpaul", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
    { id: 354, name: "Corey Anderson", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians", "Delhi Daredevils", "Royal Challengers Bangalore"] },
    { id: 355, name: "Mitchell Santner", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
    { id: 356, name: "Colin de Grandhomme", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Royal Challengers Bangalore"] },
    { id: 357, name: "Ish Sodhi", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
    { id: 358, name: "Tim Southee", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Mumbai Indians", "Royal Challengers Bangalore", "Kolkata Knight Riders"] },
    { id: 359, name: "Adam Milne", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Mumbai Indians"] },
    { id: 360, name: "Lockie Ferguson", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Gujarat Titans"] },
    { id: 361, name: "Nathan McCullum", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Pune Warriors India"] },
    { id: 362, name: "Jimmy Maher", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Daredevils"] },
    { id: 363, name: "Michael Klinger", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Kochi Tuskers Kerala"] },
    { id: 364, name: "Nathan Hauritz", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Mumbai Indians", "Royal Challengers Bangalore"] },
    { id: 365, name: "Brad Hogg", nation: "Australia", trophies: ["ICC World Cup"], iplTeams: ["Kolkata Knight Riders", "Rajasthan Royals"] },
    { id: 366, name: "Mark Cosgrove", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
    { id: 367, name: "Ashley Noffke", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
    { id: 368, name: "Andrew McDonald", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Daredevils", "Royal Challengers Bangalore"] },
    { id: 369, name: "Shaun Tait", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
    { id: 370, name: "Ashley Noffke", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
    
  ];
  
  export default players;
  