const players = [
  // Existing players with updated iplTeams (showing only modified entries)
  { id: 1, name: "Virat Kohli", nation: "India", trophies: ["ICC World Cup", "Asia Cup"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 3, name: "MS Dhoni", nation: "India", trophies: ["ICC World Cup", "T20 World Cup", "IPL"], iplTeams: ["Chennai Super Kings", "Rising Pune Supergiant"] },
  { id: 6, name: "Rohit Sharma", nation: "India", trophies: ["ICC World Cup", "IPL", "Asia Cup"], iplTeams: ["Mumbai Indians", "Deccan Chargers"] },
  { id: 7, name: "David Warner", nation: "Australia", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Delhi Capitals", "Sunrisers Hyderabad"] },
  { id: 9, name: "Ben Stokes", nation: "England", trophies: ["ICC World Cup", "T20 World Cup"], iplTeams: ["Chennai Super Kings", "Rajasthan Royals"] },
  { id: 10, name: "Rashid Khan", nation: "Afghanistan", trophies: ["Asia Cup"], iplTeams: ["Gujarat Titans", "Sunrisers Hyderabad"] },
  { id: 11, name: "Hardik Pandya", nation: "India", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Mumbai Indians", "Gujarat Titans"] },
  { id: 12, name: "Andre Russell", nation: "West Indies", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Kolkata Knight Riders", "Delhi Capitals"] },
  { id: 13, name: "Jasprit Bumrah", nation: "India", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Mumbai Indians"] },
  { id: 15, name: "Steve Smith", nation: "Australia", trophies: ["ICC World Cup", "Ashes"], iplTeams: ["Rajasthan Royals", "Pune Warriors India", "Rising Pune Supergiant", "Delhi Capitals"] },
  { id: 16, name: "Faf du Plessis", nation: "South Africa", trophies: ["Champions Trophy", "Fourth Place (2024 IPL)"], iplTeams: ["Royal Challengers Bangalore", "Chennai Super Kings", "Rising Pune Supergiant", "Delhi Capitals"] },
  { id: 17, name: "Shubman Gill", nation: "India", trophies: ["IPL"], iplTeams: ["Gujarat Titans", "Kolkata Knight Riders"] },
  { id: 19, name: "Sunil Narine", nation: "West Indies", trophies: ["T20 World Cup", "IPL", "Most Valuable Player (2024 IPL)"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 21, name: "Mohammed Shami", nation: "India", trophies: ["IPL"], iplTeams: ["Gujarat Titans", "Punjab Kings", "Delhi Capitals", "Sunrisers Hyderabad"] },
  { id: 22, name: "Trent Boult", nation: "New Zealand", trophies: ["ICC World Test Championship"], iplTeams: ["Rajasthan Royals", "Mumbai Indians", "Delhi Capitals"] },
  { id: 23, name: "KL Rahul", nation: "India", trophies: ["Asia Cup"], iplTeams: ["Lucknow Super Giants", "Punjab Kings", "Royal Challengers Bangalore", "Delhi Capitals"] },
  { id: 24, name: "Ravi Ashwin", nation: "India", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Rajasthan Royals", "Chennai Super Kings", "Punjab Kings", "Delhi Capitals"] },
  { id: 26, name: "Glenn Maxwell", nation: "Australia", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Royal Challengers Bangalore", "Punjab Kings", "Delhi Capitals"] },
  { id: 27, name: "Pat Cummins", nation: "Australia", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Kolkata Knight Riders", "Delhi Capitals", "Mumbai Indians", "Sunrisers Hyderabad"] },
  { id: 28, name: "Ishan Kishan", nation: "India", trophies: ["IPL"], iplTeams: ["Mumbai Indians", "Gujarat Lions", "Sunrisers Hyderabad"] },
  { id: 29, name: "Suryakumar Yadav", nation: "India", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Mumbai Indians", "Kolkata Knight Riders"] },
  { id: 30, name: "Ruturaj Gaikwad", nation: "India", trophies: ["IPL"], iplTeams: ["Chennai Super Kings"] },
  { id: 31, name: "Mitchell Starc", nation: "Australia", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Kolkata Knight Riders", "Royal Challengers Bangalore", "Delhi Capitals"] },
  { id: 32, name: "Sam Curran", nation: "England", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Punjab Kings", "Chennai Super Kings"] },
  { id: 33, name: "Josh Hazlewood", nation: "Australia", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Royal Challengers Bangalore", "Chennai Super Kings"] },
  { id: 34, name: "Deepak Chahar", nation: "India", trophies: ["IPL"], iplTeams: ["Chennai Super Kings", "Rising Pune Supergiant", "Mumbai Indians"] },
  { id: 35, name: "Marcus Stoinis", nation: "Australia", trophies: ["T20 World Cup"], iplTeams: ["Lucknow Super Giants", "Delhi Capitals", "Punjab Kings"] },
  { id: 36, name: "Adam Zampa", nation: "Australia", trophies: ["T20 World Cup"], iplTeams: ["Rajasthan Royals", "Royal Challengers Bangalore", "Sunrisers Hyderabad"] },
  { id: 39, name: "Shreyas Iyer", nation: "India", trophies: ["IPL", "IPL Winner (2024)"], iplTeams: ["Kolkata Knight Riders", "Delhi Capitals", "Punjab Kings"] },
  { id: 40, name: "Rishabh Pant", nation: "India", trophies: ["IPL"], iplTeams: ["Delhi Capitals", "Lucknow Super Giants"] },
  { id: 43, name: "Liam Livingstone", nation: "England", trophies: ["T20 World Cup"], iplTeams: ["Punjab Kings", "Rajasthan Royals", "Royal Challengers Bangalore"] },
  { id: 44, name: "Devdutt Padikkal", nation: "India", trophies: ["IPL"], iplTeams: ["Rajasthan Royals", "Royal Challengers Bangalore"] },
  { id: 47, name: "Varun Chakravarthy", nation: "India", trophies: ["IPL"], iplTeams: ["Kolkata Knight Riders", "Punjab Kings"] },
  { id: 49, name: "Jofra Archer", nation: "England", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Mumbai Indians", "Rajasthan Royals"] },
  { id: 50, name: "David Miller", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Punjab Kings", "Rajasthan Royals", "Lucknow Super Giants"] },
  { id: 51, name: "Bhuvneshwar Kumar", nation: "India", trophies: ["Champions Trophy", "IPL"], iplTeams: ["Sunrisers Hyderabad", "Pune Warriors India", "Royal Challengers Bangalore"] },
  { id: 52, name: "Axar Patel", nation: "India", trophies: ["Asia Cup", "IPL"], iplTeams: ["Delhi Capitals", "Punjab Kings"] },
  { id: 54, name: "Moeen Ali", nation: "England", trophies: ["ICC World Cup", "T20 World Cup"], iplTeams: ["Chennai Super Kings", "Royal Challengers Bangalore", "Kolkata Knight Riders"] },
  { id: 55, name: "Ravindra Jadeja", nation: "India", trophies: ["ICC World Cup", "Champions Trophy", "IPL"], iplTeams: ["Chennai Super Kings", "Gujarat Lions", "Rajasthan Royals"] },
  { id: 57, name: "Kuldeep Yadav", nation: "India", trophies: ["Asia Cup", "IPL"], iplTeams: ["Delhi Capitals", "Kolkata Knight Riders"] },
  { id: 58, name: "Washington Sundar", nation: "India", trophies: ["Asia Cup", "IPL"], iplTeams: ["Sunrisers Hyderabad", "Royal Challengers Bangalore", "Rising Pune Supergiant", "Gujarat Titans"] },
  { id: 59, name: "T Natarajan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad", "Punjab Kings", "Delhi Capitals"] },
  { id: 60, name: "Rahmanullah Gurbaz", nation: "Afghanistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 62, name: "Harry Brook", nation: "England", trophies: ["T20 World Cup"], iplTeams: ["Sunrisers Hyderabad", "Delhi Capitals"] },
  { id: 63, name: "Nicholas Pooran", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants", "Punjab Kings", "Sunrisers Hyderabad"] },
  { id: 64, name: "Shimron Hetmyer", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Delhi Capitals", "Royal Challengers Bangalore"] },
  { id: 70, name: "Will Jacks", nation: "England", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Mumbai Indians"] },
  { id: 71, name: "Tim David", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians", "Royal Challengers Bangalore"] },
  { id: 73, name: "Lungi Ngidi", nation: "South Africa", trophies: ["T20 World Cup"], iplTeams: ["Chennai Super Kings", "Delhi Capitals", "Royal Challengers Bangalore"] },
  { id: 74, name: "Kagiso Rabada", nation: "South Africa", trophies: ["ICC U19 World Cup"], iplTeams: ["Punjab Kings", "Delhi Capitals", "Gujarat Titans"] },
  { id: 75, name: "Jos Buttler", nation: "England", trophies: ["ICC World Cup", "IPL"], iplTeams: ["Rajasthan Royals", "Mumbai Indians", "Gujarat Titans"] },
  { id: 76, name: "Quinton de Kock", nation: "South Africa", trophies: ["IPL"], iplTeams: ["Lucknow Super Giants", "Mumbai Indians", "Delhi Capitals", "Sunrisers Hyderabad", "Kolkata Knight Riders"] },
  { id: 77, name: "Anrich Nortje", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals", "Kolkata Knight Riders"] },
  { id: 92, name: "Dinesh Karthik", nation: "India", trophies: ["IPL", "Asia Cup"], iplTeams: ["Royal Challengers Bangalore", "Kolkata Knight Riders", "Delhi Capitals", "Mumbai Indians", "Punjab Kings", "Gujarat Lions"] },
  { id: 93, name: "Ambati Rayudu", nation: "India", trophies: ["IPL"], iplTeams: ["Chennai Super Kings", "Mumbai Indians"] },
  { id: 94, name: "Manish Pandey", nation: "India", trophies: ["IPL"], iplTeams: ["Sunrisers Hyderabad", "Kolkata Knight Riders", "Royal Challengers Bangalore", "Delhi Capitals"] },
  { id: 111, name: "Nitish Kumar Reddy", nation: "India", trophies: ["Emerging Player of the Season"], iplTeams: ["Sunrisers Hyderabad"] },
  { id: 112, name: "Travis Head", nation: "Australia", trophies: ["Most 4s (2024 IPL)"], iplTeams: ["Sunrisers Hyderabad"] },
  { id: 113, name: "Abhishek Sharma", nation: "India", trophies: ["Most 6s (2024 IPL)"], iplTeams: ["Sunrisers Hyderabad"] },
  { id: 114, name: "Jake Fraser-McGurk", nation: "Australia", trophies: ["Striker of the Season (2024 IPL)"], iplTeams: ["Delhi Capitals"] },
  { id: 115, name: "Ramandeep Singh", nation: "India", trophies: ["Catch of the Season (2024 IPL)"], iplTeams: ["Mumbai Indians", "Kolkata Knight Riders"] },
  { id: 117, name: "Harshal Patel", nation: "India", trophies: ["Purple Cap (2024 IPL)"], iplTeams: ["Punjab Kings", "Sunrisers Hyderabad"] },
  { id: 118, name: "Sanju Samson", nation: "India", trophies: ["Third Place (2024 IPL)"], iplTeams: ["Rajasthan Royals"] },
  { id: 121, name: "Tilak Varma", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 122, name: "Rajat Patidar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 123, name: "Sai Sudharsan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans"] },
  { id: 124, name: "Mukesh Kumar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals"] },
  { id: 125, name: "Venkatesh Iyer", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 127, name: "Rahul Tewatia", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Rajasthan Royals"] },
  { id: 128, name: "Shivam Dube", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 129, name: "Yashasvi Jaiswal", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 130, name: "Rinku Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 131, name: "Arshdeep Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 132, name: "Ravi Bishnoi", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants"] },
  { id: 134, name: "Rahul Chahar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Mumbai Indians", "Sunrisers Hyderabad"] },
  { id: 135, name: "Krunal Pandya", nation: "India", trophies: ["IPL"], iplTeams: ["Lucknow Super Giants", "Mumbai Indians", "Royal Challengers Bangalore"] },
  { id: 136, name: "Deepak Hooda", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants", "Punjab Kings", "Chennai Super Kings"] },
  { id: 137, name: "Avesh Khan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants", "Delhi Capitals"] },
  { id: 138, name: "Riyan Parag", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 139, name: "Umran Malik", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad", "Kolkata Knight Riders"] },
  { id: 141, name: "Mohsin Khan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants"] },
  { id: 144, name: "Rajvardhan Hangargekar", nation: "India", trophies: ["ICC U19 World Cup"], iplTeams: ["Chennai Super Kings", "Lucknow Super Giants"] },
  { id: 147, name: "Gerald Coetzee", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians", "Gujarat Titans"] },
  { id: 148, name: "Noor Ahmad", nation: "Afghanistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Chennai Super Kings"] },
  { id: 149, name: "Matheesha Pathirana", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 152, name: "Akash Deep", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Lucknow Super Giants"] },
  { id: 153, name: "Mayank Yadav", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants"] },
  { id: 154, name: "Raj Angad Bawa", nation: "India", trophies: ["ICC U19 World Cup"], iplTeams: ["Punjab Kings", "Mumbai Indians"] },
  { id: 157, name: "Kumar Kartikeya", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians", "Rajasthan Royals"] },
  { id: 158, name: "Mahipal Lomror", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Gujarat Titans"] },
  { id: 159, name: "Anuj Rawat", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Gujarat Titans"] },
  { id: 162, name: "Mukesh Choudhary", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 163, name: "Simarjeet Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Sunrisers Hyderabad"] },
  { id: 164, name: "Yash Dayal", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Royal Challengers Bangalore"] },
  { id: 165, name: "Darshan Nalkande", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Delhi Capitals"] },
  { id: 166, name: "Abhinav Manohar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Sunrisers Hyderabad"] },
  { id: 167, name: "Mohit Sharma", nation: "India", trophies: ["Champions Trophy"], iplTeams: ["Gujarat Titans", "Chennai Super Kings", "Delhi Capitals"] },
  { id: 168, name: "Anukul Roy", nation: "India", trophies: ["ICC U19 World Cup"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 169, name: "Harshit Rana", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 170, name: "Suyash Sharma", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Royal Challengers Bangalore"] },
  { id: 257, name: "Mitchell Santner", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Mumbai Indians"] },
  { id: 279, name: "Yusuf Pathan", nation: "India", trophies: ["T20 World Cup", "IPL"], iplTeams: ["Rajasthan Royals", "Kolkata Knight Riders", "Sunrisers Hyderabad"] },
  // New players from IPL 2025 team lists with past teams where known
  { id: 436, name: "Devon Conway", nation: "New Zealand", trophies: ["ICC World Test Championship"], iplTeams: ["Chennai Super Kings"] },
  { id: 437, name: "Khaleel Ahmed", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Delhi Capitals", "Sunrisers Hyderabad"] },
  { id: 438, name: "Rachin Ravindra", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 439, name: "Vijay Shankar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Sunrisers Hyderabad", "Delhi Capitals", "Gujarat Titans"] },
  { id: 440, name: "Shaik Rasheed", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 441, name: "Anshul Kamboj", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 442, name: "Gurjanpreet Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 443, name: "Nathan Ellis", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Punjab Kings"] },
  { id: 444, name: "Jamie Overton", nation: "England", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 445, name: "Kamlesh Nagarkoti", nation: "India", trophies: ["ICC U19 World Cup"], iplTeams: ["Chennai Super Kings", "Kolkata Knight Riders", "Delhi Capitals"] },
  { id: 446, name: "Ramakrishnan Ghosh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 447, name: "Shreyas Gopal", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings", "Mumbai Indians", "Rajasthan Royals"] },
  { id: 448, name: "Vansh Bedi", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 449, name: "Andre Siddarth", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Chennai Super Kings"] },
  { id: 450, name: "Karun Nair", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals", "Rajasthan Royals", "Punjab Kings", "Kolkata Knight Riders"] },
  { id: 451, name: "Abhishek Porel", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals"] },
  { id: 452, name: "Tristan Stubbs", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals", "Mumbai Indians"] },
  { id: 453, name: "Sameer Rizvi", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals", "Chennai Super Kings"] },
  { id: 454, name: "Ashutosh Sharma", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals", "Punjab Kings"] },
  { id: 455, name: "Vipraj Nigam", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals"] },
  { id: 456, name: "Dushmantha Chameera", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals", "Rajasthan Royals", "Royal Challengers Bangalore", "Kolkata Knight Riders"] },
  { id: 457, name: "Donovan Ferreira", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals"] },
  { id: 458, name: "Ajay Mandal", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals"] },
  { id: 459, name: "Manvanth Kumar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals"] },
  { id: 460, name: "Tripur Akinapally Vijay", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals"] },
  { id: 461, name: "Madhav Tiwari", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Delhi Capitals"] },
  { id: 462, name: "Shahrukh Khan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Punjab Kings"] },
  { id: 463, name: "Mohammed Siraj", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Royal Challengers Bangalore", "Sunrisers Hyderabad"] },
  { id: 464, name: "Prasidh Krishna", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Kolkata Knight Riders", "Rajasthan Royals"] },
  { id: 465, name: "Nishant Sindhu", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans"] },
  { id: 466, name: "Kumar Kushagra", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Delhi Capitals"] },
  { id: 467, name: "Manav Suthar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans"] },
  { id: 468, name: "Mohammad Arshad Khan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans"] },
  { id: 469, name: "Gurnoor Singh Brar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans"] },
  { id: 470, name: "Sherfane Rutherford", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Delhi Capitals", "Kolkata Knight Riders", "Mumbai Indians"] },
  { id: 471, name: "R. Sai Kishore", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans"] },
  { id: 472, name: "Ishant Sharma", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Delhi Capitals", "Sunrisers Hyderabad", "Kolkata Knight Riders", "Rising Pune Supergiant"] },
  { id: 473, name: "Jayant Yadav", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Delhi Capitals", "Mumbai Indians"] },
  { id: 474, name: "Glenn Phillips", nation: "New Zealand", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Rajasthan Royals"] },
  { id: 475, name: "Karim Janat", nation: "Afghanistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans"] },
  { id: 476, name: "Kulwant Khejroliya", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Gujarat Titans", "Royal Challengers Bangalore", "Kolkata Knight Riders"] },
  { id: 477, name: "Angkrish Raghuvanshi", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 478, name: "Vaibhav Arora", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Punjab Kings"] },
  { id: 479, name: "Mayank Markande", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Mumbai Indians", "Rajasthan Royals"] },
  { id: 480, name: "Rovman Powell", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Delhi Capitals"] },
  { id: 481, name: "Spencer Johnson", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Gujarat Titans"] },
  { id: 482, name: "Luvnith Sisodia", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders"] },
  { id: 483, name: "Ajinkya Rahane", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Kolkata Knight Riders", "Mumbai Indians", "Rajasthan Royals", "Chennai Super Kings", "Rising Pune Supergiant"] },
  { id: 484, name: "Aiden Markram", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants", "Sunrisers Hyderabad"] },
  { id: 485, name: "Abdul Samad", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants", "Sunrisers Hyderabad"] },
  { id: 486, name: "Aryan Juyal", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants"] },
  { id: 487, name: "Himmat Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants", "Royal Challengers Bangalore"] },
  { id: 488, name: "M. Siddharth", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants", "Kolkata Knight Riders", "Delhi Capitals"] },
  { id: 489, name: "Digvesh Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants"] },
  { id: 490, name: "Shahbaz Ahmed", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants", "Royal Challengers Bangalore", "Sunrisers Hyderabad"] },
  { id: 491, name: "Akash Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants", "Chennai Super Kings"] },
  { id: 492, name: "Shamar Joseph", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants"] },
  { id: 493, name: "Prince Yadav", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants"] },
  { id: 494, name: "Yuvraj Chaudhary", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants"] },
  { id: 495, name: "Arshin Kulkarni", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants"] },
  { id: 496, name: "Matthew Breetzke", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Lucknow Super Giants"] },
  { id: 497, name: "Naman Dhir", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 498, name: "Robin Minz", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 499, name: "Karn Sharma", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians", "Royal Challengers Bangalore", "Sunrisers Hyderabad", "Chennai Super Kings"] },
  { id: 500, name: "Ryan Rickelton", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 501, name: "Allah Ghazanfar", nation: "Afghanistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 502, name: "Ashwani Kumar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 503, name: "Shrijith Krishnan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 504, name: "Venkat Satyanarayana Raju", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 505, name: "Bevon Jacobs", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 506, name: "Arjun Tendulkar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 507, name: "Lizaad Williams", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 508, name: "Vignesh Puthur", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Mumbai Indians"] },
  { id: 509, name: "Yuzvendra Chahal", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Mumbai Indians", "Royal Challengers Bangalore", "Rajasthan Royals"] },
  { id: 510, name: "Shashank Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Delhi Capitals", "Sunrisers Hyderabad"] },
  { id: 511, name: "Prabhsimran Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 512, name: "Harpreet Brar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 513, name: "Vijaykumar Vyshak", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Royal Challengers Bangalore"] },
  { id: 514, name: "Yash Thakur", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Lucknow Super Giants"] },
  { id: 515, name: "Marco Jansen", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Sunrisers Hyderabad", "Mumbai Indians"] },
  { id: 516, name: "Josh Inglis", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 517, name: "Azmatullah Omarzai", nation: "Afghanistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Gujarat Titans"] },
  { id: 518, name: "Harnoor Pannu", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 519, name: "Kuldeep Sen", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Rajasthan Royals"] },
  { id: 520, name: "Priyansh Arya", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 521, name: "Aaron Hardie", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 522, name: "Musheer Khan", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 523, name: "Suryansh Shedge", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 524, name: "Xavier Bartlett", nation: "Australia", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 525, name: "Pyla Avinash", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings"] },
  { id: 526, name: "Pravin Dubey", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Delhi Capitals"] },
  { id: 527, name: "Nehal Wadhera", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Punjab Kings", "Mumbai Indians"] },
  { id: 528, name: "Dhruv Jurel", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 529, name: "Sandeep Sharma", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Punjab Kings", "Sunrisers Hyderabad"] },
  { id: 530, name: "Wanindu Hasaranga", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Royal Challengers Bangalore", "Sunrisers Hyderabad"] },
  { id: 531, name: "Maheesh Theekshana", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Chennai Super Kings"] },
  { id: 532, name: "Akash Madhwal", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Mumbai Indians"] },
  { id: 533, name: "Nitish Rana", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Kolkata Knight Riders", "Mumbai Indians"] },
  { id: 534, name: "Tushar Deshpande", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Delhi Capitals", "Chennai Super Kings"] },
  { id: 535, name: "Shubham Dubey", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 536, name: "Yudhvir Charak", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Lucknow Super Giants"] },
  { id: 537, name: "Fazal Farooqi", nation: "Afghanistan", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Sunrisers Hyderabad"] },
  { id: 538, name: "Vaibhav Suryavanshi", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 539, name: "Kwena Maphaka", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 540, name: "Kunal Rathore", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals"] },
  { id: 541, name: "Ashok Sharma", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Rajasthan Royals", "Kolkata Knight Riders"] },
  { id: 542, name: "Jitesh Sharma", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Punjab Kings"] },
  { id: 543, name: "Rasikh Dar", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Delhi Capitals"] },
  { id: 544, name: "Swapnil Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Punjab Kings", "Mumbai Indians"] },
  { id: 545, name: "Romario Shepherd", nation: "West Indies", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore", "Lucknow Super Giants", "Mumbai Indians"] },
  { id: 546, name: "Nuwan Thushara", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 547, name: "Manoj Bhandage", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 548, name: "Jacob Bethell", nation: "England", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 549, name: "Swastik Chhikara", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 550, name: "Abhinandan Singh", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 551, name: "Mohit Rathee", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Royal Challengers Bangalore"] },
  { id: 552, name: "Heinrich Klaasen", nation: "South Africa", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad", "Royal Challengers Bangalore", "Rajasthan Royals"] },
  { id: 553, name: "Atharva Taide", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad", "Punjab Kings"] },
  { id: 554, name: "Zeeshan Ansari", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad"] },
  { id: 555, name: "Jaydev Unadkat", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad", "Kolkata Knight Riders", "Royal Challengers Bangalore", "Delhi Capitals", "Rajasthan Royals", "Mumbai Indians"] },
  { id: 556, name: "Brydon Carse", nation: "England", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad"] },
  { id: 557, name: "Kamindu Mendis", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad"] },
  { id: 558, name: "Aniket Verma", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad"] },
  { id: 559, name: "Eshan Malinga", nation: "Sri Lanka", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad"] },
  { id: 560, name: "Sachin Baby", nation: "India", trophies: ["No Major ICC Trophy"], iplTeams: ["Sunrisers Hyderabad", "Royal Challengers Bangalore", "Rajasthan Royals"] }
];

export default players;